#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * NexaPHP Console Application
 * 
 * This is the main entry point for console commands.
 * It provides Artisan-like functionality for the framework.
 * 
 * @package NexaPHP
 */

// Check if running from CLI
if (PHP_SAPI !== 'cli') {
    exit('This script can only be run from the command line.');
}

// Application banner
$banner = <<<BANNER
    ________   _______      ___    ___ ___  ________      
|\   ___  \|\  ___ \    |\  \  /  /|\  \|\   ____\     
\ \  \\ \  \ \   __/|   \ \  \/  / | \  \ \  \___|_    
 \ \  \\ \  \ \  \_|/__  \ \    / / \ \  \ \_____  \   
  \ \  \\ \  \ \  \_|\ \  /     \/   \ \  \|____|\  \  
   \ \__\\ \__\ \_______\/  /\   \    \ \__\____\_\  \ 
    \|__| \|__|\|_______/__/ /\ __\    \|__|\_________\
                        |__|/ \|__|        \|_________|
                                                       
                                                       
                                       
  NexaPHP Framework - Console Tool
  Version 1.0.0

BANNER;

echo $banner;

// Bootstrap the console application
$app = require __DIR__ . '/bootstrap/console.php';

// Create console kernel
$kernel = $app->make(NexaCore\Console\ConsoleKernel::class);

// Run the console application
$status = $kernel->handle(
    new Symfony\Component\Console\Input\ArgvInput(),
    new Symfony\Component\Console\Output\ConsoleOutput()
);

// Terminate the application
$kernel->terminate(new Symfony\Component\Console\Input\ArgvInput(), $status);

exit($status);